version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "delivery_service"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "database"
  employee-system-backend:
    image: vorstu/delivery-service-backend:0.0.1-SNAPSHOT
    environment:
      DATABASESERVER_PORT: "5432"
      SPRING_PROFILES_ACTIVE : "docker"

    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge